CRM\SecurityBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: CRM\SecurityBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
        roleId:
            type: integer
            column: role_id
    lifecycleCallbacks: {  }

    manyToOne:
        role:
            targetEntity: Role
            inversedBy: user
            joinColumn:
                name: role_id
                referencedColumnName: id
            cascade: ['persist']

    oneToMany:
        project_user_status:
            targetEntity: CRM\AppBundle\Entity\Project_User_Status
            mappedBy: user
        project:
            targetEntity: CRM\AppBundle\Entity\Project
            mappedBy: user