
index:
    path:     /
    defaults: { _controller: AppBundle:Main:index }

initiator:
    path:     /initiator
    defaults: { _controller: AppBundle:Role:initiator }

admin:
    path:     /admin
    defaults: { _controller: AppBundle:Role:admin }

production_director:
    path:     /productionDirector
    defaults: { _controller: AppBundle:Role:productionDirector }

financial_director:
    path:     /financialDirector
    defaults: { _controller: AppBundle:Role:financialDirector }

financial_controller:
    path:     /financialController
    defaults: { _controller: AppBundle:Role:financialController }
