<?php

namespace CRM\AppBundle\Repository;

/**
 * Approval_SchemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Approval_SchemaRepository extends \Doctrine\ORM\EntityRepository
{
}
