<?php

namespace CRM\AppBundle\Repository;

/**
 * Project_User_StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Project_User_StatusRepository extends \Doctrine\ORM\EntityRepository
{
}
