AppBundle\Entity\Project:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProjectRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        npv:
            type: integer
            column: NPV
        irr:
            type: integer
            column: IRR
        cashFlow1:
            type: float
            column: cash_flow_1
        cashFlow2:
            type: float
            column: cash_flow_2
        cashFlow3:
            type: float
            column: cash_flow_3
        rop1:
            type: float
            column: ROP_1
        rop2:
            type: float
            column: ROP_2
        rop3:
            type: float
            column: ROP_3
        cann1:
            type: float
            column: CANN_1
        cann2:
            type: float
            column: CANN_2
        cann3:
            type: float
            column: CANN_3
        createdAt:
            type: datetime
            column: created_at
        statusId:
            type: integer
            column: status_id
        approvedAt:
            type: datetime
            column: approved_at
        userId:
            type: integer
            column: user_id
        categoryId:
            type: integer
            column: category_id
    lifecycleCallbacks: {  }

    manyToOne:
        status:
            targetEntity: Status
            inversedBy: projects
            joinColumn:
                name: status_id
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: projects
            joinColumn:
                name: user_id
                referencedColumnName: id
        category:
            targetEntity: Category
            inversedBy: projects
            joinColumn:
                name: category_id
                referencedColumnName: id

